### ISSUE TITLE
Payload decoding in the browser wallet of the CIS3 standard

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-browser-wallet#279]
**Task description**
If a smart contract implements the CIS3 standard (sponsored transactions). The sponsored transaction `message` will be sent to the Concordium browser wallet to be signed by the user. Currently, when providing the `schema` to the browser wallet, it can decode the object except for the payload field which is an array of bytes.

Feature to be added to the browser wallet:
The browser wallet can also decode the payload field by looking up the parameter schema of the `entry_point_name` and using this schema to decode the payload. The payload is the input parameter that is sent to the `entry_point_name`. 

![DecodingOfSigningOfMessage](https://user-images.githubusercontent.com/13039169/232790023-a950347b-ef65-42f4-b4ab-584641161c6b.png)

CIS3 standard:
https://github.com/Concordium/concordium-update-proposals/pull/41

**Comment by limemloh** [comment]
Since the current approach is to use `signMessage` function provided by the wallet, we don't really know what we are signing, and we can't really deserialize the message and look whether it is for CIS-3 reliably.
A solution could be to extend the wallet API with `signCis3Message` which is tailored for this.

**Comment by abizjak** [comment]
https://github.com/Concordium/concordium-dapp-examples/issues/77
